# Generated by Django 4.2.20 on 2025-04-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=200)),
                ('descricaoProduto', models.TextField()),
                ('precoProduto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagemProduto', models.ImageField(upload_to='imagens/')),
                ('qtdeEstoque', models.IntegerField()),
            ],
        ),
    ]
